path:
  ckpt_path: "D:/Side/BackUp/output/US_Female/ckp"
  log_path: "D:/Side/BackUp/output/US_Female/log"
  result_path: "D:/Side/BackUp/output/US_Female/result"
  pretrained: True
  pretrained_path: "D:/Side/BackUp/pretrain/900000.pth.tar"
optimizer:
  batch_size: 48
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: []
  anneal_rate: 1.0
  device: "cuda:0"
step:
  total_step: 160000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 10000